<script lang="ts">
  import { base } from '$app/paths';
</script>

<svelte:head>
  <title>What is a UUID v5 and Why Use It? | UUID v5 Generator Blog</title>
  <meta name="description" content="Learn what UUID v5 is, how namespace-based identifiers work, and why they're superior for deterministic, reproducible IDs in modern systems." />
  <meta property="og:title" content="What is a UUID v5 and Why Use It?" />
  <meta property="og:description" content="Discover the power of deterministic UUIDs using SHA-1 and namespaces — perfect for distributed systems, caching, and migrations." />
  <meta property="og:url" content="{base}/blog/posts/post1" />
  <meta property="og:type" content="article" />
  <meta name="twitter:card" content="summary_large_image" />
</svelte:head>

<div class="container fade-in post-layout">
  <div class="breadcrumbs">
    <a href="{base}/blog">Blog</a>
    <span>/</span>
    <p>What is a UUID v5 and Why Use It?</p>
  </div>

  <article class="prose">
    <h1>What is a UUID v5 and Why Use It?</h1>
    <p class="post-meta">Published: November 28, 2025</p>

    <p>A <strong>UUID v5</strong> is a 128-bit identifier generated by applying SHA-1 to a namespace UUID and a name. Unlike random UUIDs (v4), v5 is <strong>fully deterministic</strong>: the same namespace + name combination will always produce the exact same UUID — forever, across any system, anywhere in the world.</p>

    <p>This makes UUID v5 uniquely powerful in distributed architectures where consistency and reproducibility matter more than pure randomness.</p>

    <h2>How UUID v5 Works</h2>
    <p>The process is defined in RFC 4122:</p>
    <ol>
      <li>Take a namespace UUID (e.g., the official DNS namespace: <code>6ba7b810-9dad-11d1-80b4-00c04fd430c8</code>)</li>
      <li>Combine it with any string (the "name") — like a domain, URL, username, or file path</li>
      <li>Run SHA-1 on the combined bytes</li>
      <li>Take the first 128 bits, set version = 5 and variant = RFC 4122</li>
      <li>Result: a perfectly valid, globally unique, deterministic UUID</li>
    </ol>

    <h2>Why Choose v5 Over v4 or v1?</h2>
    <p>While UUID v4 is excellent for public tokens and v1 offers sortability, v5 combines the best of both worlds when you need:</p>
    <ul>
      <li><strong>Reproducibility</strong> — migrate data, rebuild caches, sync systems with zero drift</li>
      <li><strong>Human-readable mapping</strong> — know exactly which input created which ID</li>
      <li><strong>No coordination</strong> — generate consistent IDs without a central authority</li>
      <li><strong>Security through obscurity not required</strong> — names can be public (e.g., URLs)</li>
    </ul>

    <h2>Real-World Use Cases</h2>
    <p>UUID v5 shines in:</p>
    <ul>
      <li>Content-addressable storage (IPFS, Git)</li>
      <li>Cache keys from URLs or usernames</li>
      <li>Entity IDs in microservices ("user:alice@example.com" → same UUID everywhere)</li>
      <li>Configuration identifiers across environments</li>
      <li>Event sourcing and CQRS systems</li>
    </ul>

    <h2>FAQ</h2>
    <details>
      <summary>Is UUID v5 still secure?</summary>
      <p>Yes — when used correctly. The namespace acts as a salt. Never use sensitive data as the name.</p>
    </details>
    <details>
      <summary>Can two different names produce the same v5 UUID?</summary>
      <p>Only with an astronomically unlikely SHA-1 collision (theoretical, not practical).</p>
    </details>
    <details>
      <summary>Should I use v5 as a primary key?</summary>
      <p>Absolutely — especially in distributed databases. It prevents ID conflicts during merges.</p>
    </details>

    <p class="italic-note">
      UUID v5 isn't just another identifier — it's a contract: same input, same output, everywhere, forever.
    </p>
  </article>
</div>

<style>
  .post-layout {
    max-width: 800px;
    padding-top: 2rem;
    padding-bottom: 4rem;
  }

  .breadcrumbs {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 1.5rem;
    font-size: 0.9rem;
    color: var(--text-secondary);
  }
  .breadcrumbs a {
    color: var(--accent-secondary);
  }
  .breadcrumbs a:hover {
    text-decoration: underline;
  }
  .breadcrumbs p {
    margin: 0;
  }

  .prose {
    line-height: 1.8;
  }

  .prose .post-meta {
    color: var(--text-secondary);
    font-size: 0.9rem;
    margin-bottom: 2rem;
    border-bottom: 1px solid var(--border-color);
    padding-bottom: 1rem;
  }

  .prose h1, .prose h2 {
    color: var(--accent-secondary);
  }

  .prose h1 {
    font-size: 2.5rem;
    margin-bottom: 0.5rem;
  }

  .prose h2 {
    margin-top: 2.5rem;
    border-bottom: 1px solid var(--secondary-bg);
    padding-bottom: 0.5rem;
  }
  
  .prose p {
    color: var(--text-primary);
  }

  .prose ul {
    list-style-type: '→ ';
    padding-left: 1.5rem;
    color: var(--text-primary);
  }
  .prose ul li::marker {
    color: var(--accent-primary);
  }
  .prose ul li {
    padding-left: 0.5rem;
    margin-bottom: 0.5rem;
  }

  .prose details {
    background: var(--secondary-bg);
    border: 1px solid var(--border-color);
    border-radius: 6px;
    padding: 1rem;
    margin-bottom: 1rem;
    transition: background-color 0.2s ease;
  }
  
  .prose details[open] {
    background-color: var(--card-bg);
  }

  .prose summary {
    cursor: pointer;
    font-weight: 600;
    color: var(--accent-secondary);
    list-style: none;
  }
  
  .prose summary::-webkit-details-marker {
    display: none;
  }
  
  .prose summary::before {
    content: '+';
    margin-right: 0.75rem;
    color: var(--accent-primary);
    font-weight: bold;
    display: inline-block;
    transition: transform 0.2s ease;
  }

  .prose details[open] summary::before {
    transform: rotate(45deg);
  }
  
  .prose details p {
    margin-top: 1rem;
    padding-left: 1.5rem;
    border-left: 2px solid var(--accent-primary);
    color: var(--text-secondary);
  }

  .prose .italic-note {
    font-style: italic;
    color: var(--text-secondary);
    text-align: center;
    margin-top: 3rem;
  }
</style>
